services:
  - type: web
    name: apex-product-app
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: apex-product-app
