// MongoDB database manager for Apex Product App
const mongoose = require('mongoose');
const crypto = require('node:crypto');
const { seedProducts, seedReviews } = require('./seed.js');

const productSchema = new mongoose.Schema({
  id: { type: Number, unique: true, index: true }, name: String, sku: { type: String, unique: true }, category: { type: String, index: true }, brand: String,
  price: Number, compare_at_price: Number, stock: Number, rating: Number, reviews_count: Number, description: String, image_url: String,
  secondary_images: [String], features: [String], tags: [String], created_at: String
}, { versionKey: false });
const reviewSchema = new mongoose.Schema({ id: { type: Number, unique: true }, product_id: { type: Number, index: true }, user_name: String, user_avatar: String, rating: Number, title: String, comment: String, created_at: String }, { versionKey: false });
const orderSchema = new mongoose.Schema({ id: { type: String, unique: true }, customer_name: String, customer_email: String, shipping_address: String, subtotal: Number, discount: Number, shipping: Number, tax: Number, total: Number, promo_code: String, status: String, created_at: String, items: [{ product_id: Number, product_name: String, quantity: Number, price: Number }] }, { versionKey: false });
const userSchema = new mongoose.Schema({ name: String, email: { type: String, unique: true }, password_hash: String, created_at: String }, { versionKey: false });
const Product = mongoose.models.Product || mongoose.model('Product', productSchema);
const Review = mongoose.models.Review || mongoose.model('Review', reviewSchema);
const Order = mongoose.models.Order || mongoose.model('Order', orderSchema);
const User = mongoose.models.User || mongoose.model('User', userSchema);
let connectionPromise;

async function connectDatabase() {
  if (!process.env.MONGO_URI) throw new Error('MONGO_URI is required. Configure MongoDB Atlas before starting the server.');
  if (!connectionPromise) connectionPromise = mongoose.connect(process.env.MONGO_URI, { dbName: process.env.MONGO_DB_NAME || 'apex-product-app' }).then(async connection => { if (await Product.countDocuments() === 0) await seedDatabase(); return connection; }).catch(error => { connectionPromise = null; throw error; });
  return connectionPromise;
}
async function seedDatabase() {
  await Product.deleteMany({}); await Review.deleteMany({});
  await Product.insertMany(seedProducts.map(product => ({ ...product, secondary_images: JSON.parse(product.secondary_images), features: JSON.parse(product.features), tags: JSON.parse(product.tags) })));
  await Review.insertMany(seedReviews.map((review, index) => ({ ...review, id: index + 1 })));
}
async function resetDatabase() { await connectDatabase(); await Order.deleteMany({}); await seedDatabase(); return { success: true, message: 'Database reseeded successfully.' }; }
async function getProducts({ q = '', category = '', brand = '', minPrice = 0, maxPrice = 1000000, rating = 0, inStock = false, sort = 'featured', page = 1, limit = 24 } = {}) {
  await connectDatabase(); const filter = {};
  if (q && q.trim()) filter.$or = ['name', 'description', 'brand', 'tags'].map(field => ({ [field]: { $regex: q.trim(), $options: 'i' } }));
  if (category && category.trim()) filter.category = category.trim(); if (brand && brand.trim()) filter.brand = brand.trim();
  if (Number(minPrice) > 0 || Number(maxPrice) < 1000000) filter.price = { ...(Number(minPrice) > 0 ? { $gte: Number(minPrice) } : {}), ...(Number(maxPrice) < 1000000 ? { $lte: Number(maxPrice) } : {}) };
  if (Number(rating) > 0) filter.rating = { $gte: Number(rating) }; if (inStock === true || inStock === 'true' || inStock === '1') filter.stock = { $gt: 0 };
  const parsedPage = Math.max(1, parseInt(page, 10) || 1); const parsedLimit = Math.max(1, Math.min(100, parseInt(limit, 10) || 24));
  const sortMap = { 'price-low': { price: 1 }, 'price-high': { price: -1 }, rating: { rating: -1, reviews_count: -1 }, reviews: { reviews_count: -1 }, 'name-asc': { name: 1 }, featured: { rating: -1, id: 1 } };
  const [total, products] = await Promise.all([Product.countDocuments(filter), Product.find(filter).sort(sortMap[sort] || sortMap.featured).skip((parsedPage - 1) * parsedLimit).limit(parsedLimit).lean()]);
  return { products, pagination: { total, page: parsedPage, limit: parsedLimit, totalPages: Math.ceil(total / parsedLimit) } };
}
async function getProductById(id) { await connectDatabase(); const product = await Product.findOne({ id: Number(id) }).lean(); if (!product) return null; const [reviews, related] = await Promise.all([Review.find({ product_id: Number(id) }).sort({ id: -1 }).lean(), Product.find({ category: product.category, id: { $ne: Number(id) } }).select('id name price rating image_url category -_id').limit(4).lean()]); return { ...product, reviews, related }; }
async function nextId(model) { const last = await model.findOne().sort({ id: -1 }).select('id').lean(); return (last?.id || 0) + 1; }
async function createProduct(data) { await connectDatabase(); const id = await nextId(Product); await Product.create({ id, name: data.name, sku: data.sku || `SKU-${Date.now().toString().slice(-6)}`, category: data.category || 'General', brand: data.brand || 'Apex', price: Number(data.price) || 0, compare_at_price: data.compare_at_price ? Number(data.compare_at_price) : null, stock: Number(data.stock) || 0, rating: Number(data.rating) || 5, reviews_count: 0, description: data.description || '', image_url: data.image_url || seedProducts[0].image_url, secondary_images: data.secondary_images || [], features: data.features || [], tags: data.tags || [], created_at: new Date().toISOString() }); return getProductById(id); }
async function updateProduct(id, data) { await connectDatabase(); const product = await Product.findOneAndUpdate({ id: Number(id) }, { $set: data }, { returnDocument: 'after', runValidators: true }).lean(); return product ? getProductById(id) : null; }
async function deleteProduct(id) { await connectDatabase(); const result = await Product.deleteOne({ id: Number(id) }); await Review.deleteMany({ product_id: Number(id) }); return result.deletedCount > 0; }
async function adjustStock(id, delta) { await connectDatabase(); const product = await Product.findOne({ id: Number(id) }); if (!product) return null; product.stock = Math.max(0, product.stock + Number(delta)); await product.save(); return { id: Number(id), stock: product.stock }; }
async function addReview(productId, data) { await connectDatabase(); if (!await Product.exists({ id: Number(productId) })) return null; const rating = Math.max(1, Math.min(5, parseInt(data.rating, 10) || 5)); await Review.create({ id: await nextId(Review), product_id: Number(productId), user_name: data.user_name || 'Verified Customer', user_avatar: data.user_avatar || '', rating, title: data.title || 'Product Feedback', comment: data.comment || '', created_at: new Date().toISOString() }); const stats = await Review.aggregate([{ $match: { product_id: Number(productId) } }, { $group: { _id: null, count: { $sum: 1 }, average: { $avg: '$rating' } } }]); await Product.updateOne({ id: Number(productId) }, { rating: Math.round(stats[0].average * 10) / 10, reviews_count: stats[0].count }); return getProductById(productId); }
async function getCategories() { await connectDatabase(); return Product.aggregate([{ $group: { _id: '$category', count: { $sum: 1 } } }, { $project: { _id: 0, name: '$_id', count: 1 } }, { $sort: { count: -1 } }]); }
async function getAnalytics() { await connectDatabase(); const [stats, low, out, categories, orders] = await Promise.all([Product.aggregate([{ $group: { _id: null, totalProducts: { $sum: 1 }, totalInventoryUnits: { $sum: '$stock' }, totalInventoryValue: { $sum: { $multiply: ['$price', '$stock'] } }, averagePrice: { $avg: '$price' }, averageRating: { $avg: '$rating' } } }]), Product.countDocuments({ stock: { $gt: 0, $lte: 5 } }), Product.countDocuments({ stock: 0 }), Product.aggregate([{ $group: { _id: '$category', count: { $sum: 1 }, stock: { $sum: '$stock' }, avgPrice: { $avg: '$price' } } }, { $project: { _id: 0, category: '$_id', count: 1, stock: 1, avgPrice: { $round: ['$avgPrice', 2] } } }, { $sort: { count: -1 } }]), Order.aggregate([{ $group: { _id: null, totalOrders: { $sum: 1 }, totalRevenue: { $sum: '$total' } } }])]); const p = stats[0] || {}, o = orders[0] || {}; return { overview: { totalProducts: p.totalProducts || 0, totalInventoryUnits: p.totalInventoryUnits || 0, totalInventoryValue: Math.round((p.totalInventoryValue || 0) * 100) / 100, averagePrice: Math.round((p.averagePrice || 0) * 100) / 100, averageRating: Math.round((p.averageRating || 0) * 10) / 10, lowStockCount: low, outOfStockCount: out, totalOrders: o.totalOrders || 0, totalRevenue: Math.round((o.totalRevenue || 0) * 100) / 100 }, categories }; }
async function createOrder({ customer_name, customer_email, shipping_address, items, promo_code, discount = 0 }) { await connectDatabase(); if (!Array.isArray(items) || !items.length) throw new Error('Order must contain at least one item'); const products = await Product.find({ id: { $in: items.map(item => Number(item.id)) } }); const byId = new Map(products.map(product => [product.id, product])); for (const item of items) { const product = byId.get(Number(item.id)); if (!product) throw new Error(`Product with ID ${item.id} not found.`); if (product.stock < item.quantity) throw new Error(`Insufficient stock for "${product.name}". Available: ${product.stock}, requested: ${item.quantity}.`); } const orderId = `ORD-${Date.now().toString(36).toUpperCase()}-${Math.floor(Math.random() * 1000)}`, now = new Date().toISOString(); const subtotal = items.reduce((sum, item) => sum + byId.get(Number(item.id)).price * item.quantity, 0), discountAmount = Number(discount) || 0, tax = Math.round(Math.max(0, subtotal - discountAmount) * 0.08 * 100) / 100, shipping = subtotal > 150 ? 0 : 15, total = Math.max(0, Math.round((subtotal - discountAmount + tax + shipping) * 100) / 100); await Order.create({ id: orderId, customer_name: customer_name || 'Guest Shopper', customer_email: customer_email || 'shopper@example.com', shipping_address: shipping_address || '', subtotal, discount: discountAmount, shipping, tax, total, promo_code: promo_code || null, status: 'confirmed', created_at: now, items: items.map(item => ({ product_id: Number(item.id), product_name: byId.get(Number(item.id)).name, quantity: item.quantity, price: byId.get(Number(item.id)).price })) }); await Promise.all(items.map(item => Product.updateOne({ id: Number(item.id) }, { $inc: { stock: -Number(item.quantity) } }))); return { orderId, status: 'confirmed', customer: { name: customer_name, email: customer_email, address: shipping_address }, breakdown: { subtotal: Math.round(subtotal * 100) / 100, discount: discountAmount, shipping, tax, total }, items, createdAt: now }; }
async function getOrders() { await connectDatabase(); return Order.find().sort({ created_at: -1 }).limit(50).lean(); }
function hashPassword(password, salt = crypto.randomBytes(16).toString('hex')) { return new Promise((resolve, reject) => crypto.scrypt(password, salt, 64, (error, key) => error ? reject(error) : resolve(`${salt}:${key.toString('hex')}`))); }
async function createUser(name, email, password) { await connectDatabase(); const normalizedEmail = email.trim().toLowerCase(); if (await User.exists({ email: normalizedEmail })) throw new Error('An account with this email already exists.'); const user = await User.create({ name: name.trim(), email: normalizedEmail, password_hash: await hashPassword(password), created_at: new Date().toISOString() }); return { id: user._id.toString(), name: user.name, email: user.email }; }
async function authenticateUser(email, password) { await connectDatabase(); const user = await User.findOne({ email: email.trim().toLowerCase() }).lean(); if (!user) return null; const [salt, storedHash] = user.password_hash.split(':'); const hash = await hashPassword(password, salt); if (hash.split(':')[1] !== storedHash) return null; return { id: user._id.toString(), name: user.name, email: user.email }; }

async function closeDatabase() { connectionPromise = null; if (mongoose.connection.readyState !== 0) await mongoose.disconnect(); }

module.exports = { connectDatabase, closeDatabase, resetDatabase, getProducts, getProductById, createProduct, updateProduct, deleteProduct, adjustStock, addReview, getCategories, getAnalytics, createOrder, getOrders, createUser, authenticateUser };